version: "1"
services:
  core:
    build:
      context: .
      dockerfile: ./docker/core/Dockerfile
      args:
        - ARCH=$ARCH
    volumes:
      - ./jsybuben-core:/jsybuben-core:rw
  db:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=passw0rd
    volumes:
      - ./docker/db/initsql:/docker-entrypoint-initdb.d
  rest:
    build:
      context: .
      dockerfile: ./docker/rest/Dockerfile
      args:
        - ARCH=$ARCH
    ports:
      - 3000:3000
    volumes:
      - ./jsybuben-core:/jsybuben-core:rw
      - ./jsybuben-rest:/jsybuben-rest:rw
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
      args:
        - ARCH=$ARCH
#    depends_on:
#      - rest
    ports:
      - 3000:3000
    volumes:
      - ./jsybuben-core:/jsybuben-core:rw
      - ./jsybuben-client:/jsybuben-client:rw
