version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./jsybuben-api:/jsybuben-api:rw
  cli:
    build:
      context: .
      dockerfile: ./docker/cli/Dockerfile
    volumes:
      - ./jsybuben-api:/jsybuben-api:rw
      - ./jsybuben-cli:/jsybuben-cli:rw
  rest:
    build:
      context: .
      dockerfile: ./docker/rest/Dockerfile
    ports:
      - "8888"
    volumes:
      - ./jsybuben-api:/jsybuben-api:rw
      - ./jsybuben-rest:/jsybuben-rest:rw
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - "3000"
    volumes:
      - ./jsybuben-api:/jsybuben-api:rw
      - ./jsybuben-client:/jsybuben-client:rw
