version: "3.8"
services:
  core:
    build:
      context: .
      dockerfile: ./docker/core/Dockerfile
    volumes:
      - ./jsybuben-core:/jsybuben-core:rw
  rest:
    build:
      context: .
      dockerfile: ./docker/rest/Dockerfile
    ports:
      - "8888"
    volumes:
      - ./jsybuben-core:/jsybuben-core:rw
      - ./jsybuben-rest:/jsybuben-rest:rw
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - "3000"
    volumes:
      - ./jsybuben-core:/jsybuben-core:rw
      - ./jsybuben-client:/jsybuben-client:rw
