version: "1"
services:
  core:
    build:
      context: .
      dockerfile: ./docker/core/Dockerfile
    volumes:
      - ./jsybuben-core:/jsybuben-core:rw
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    volumes:
      - ./jsybuben-core:/jsybuben-core:rw
      - ./jsybuben-client:/jsybuben-client:rw
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./jsybuben-core:/jsybuben-core:rw
      - ./jsybuben-server:/jsybuben-server:rw
