version: "1"
services:
  core:
    build:
      context: .
      dockerfile: ./docker/core/Dockerfile
    volumes:
      - ./jsybuben-core:/jsybuben-core:rw
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    volumes:
      - ./jsybuben-core:/jsybuben-core:rw
      - ./jsybuben-client:/jsybuben-client:rw
  rest:
    build:
      context: .
      dockerfile: ./docker/rest/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./jsybuben-core:/jsybuben-core:rw
      - ./jsybuben-rest:/jsybuben-rest:rw
